# Generated by Django 3.1 on 2020-08-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_used_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_coupon',
        ),
    ]
